### ISSUE TITLE
Deserialization of enum iterables is broken due to duplicate variables

### ISSUE THREAD

**Issue by Skycoder42** [tnc1997/dart-xml-serializable#25] opened 2022-10-25 14:39 UTC
**Describe the bug**
The generated code is unable to handle enum lists, as multiple methods use `e`, overshadowing each other.

**Current behavior**
Consider the following code:

```dart
@xml.XmlEnum()
enum AccessType {
  @xml.XmlValue('SiteA')
  siteA,
  @xml.XmlValue('SiteBeta')
  siteB;
}

@xml.XmlSerializable(createMixin: true)
@xml.XmlRootElement(name: 'Permissions')
class Permissions with _$PermissionsXmlSerializableMixin {
  @xml.XmlElement(name: 'Access')
  final List<AccessType>? accessTypes;

  const Permissions({
    required this.accessTypes,
  });

  factory Permissions.fromXmlElement(XmlElement element) =>
      _$PermissionsFromXmlElement(element);
}
```

The generator will generate the following snippet for the `_$PermissionsFromXmlElement` method:

```dart
Permissions _$PermissionsFromXmlElement(XmlElement element) {
  final accessTypes = element
      .getElements('Access')
      ?.map((e) => e.getText())
      .whereType<String>();
  return Permissions(
      accessTypes: accessTypes
          ?.map((e) => _$AccessTypeEnumMap.entries // HERE: e is defined  
              .singleWhere((e) => e.value == e, // HERE: e is defined again 
                  orElse: () => throw ArgumentError(
                      '`$e` is not one of the supported values: ${_$AccessTypeEnumMap.values.join(', ')}'))
              .key)
          .toList());
}
```

As you can see, `e` i used both in `map` and `singleWhere`, which leads to the second always being false (as `e.value == e` is obviously never true).

**Expected behavior**
It should work correctly and thus use two different variables. Recommendation: Use long names like `element` and `enumEntry`. Or even better generated names like `accessTypesElement` and `accessTypeEnumEntry`.

**Comment by Skycoder42** [comment] 2022-10-25 14:49
Possible places in code: 
- lib/src/serializer_generators/enum_serializer_generator.dart:41
- lib/src/serializer_generators/iterable_serializer_generator.dart:5

**Comment by tnc1997** [comment] 2022-10-25 15:01
Hi @Skycoder42, thank you very much for reporting this bug, I will aim to develop and release a fix this week.

**Comment by tnc1997** [comment] 2022-10-25 19:49
Hi @Skycoder42, could I get you to verify that the issue is resolved by the changes on the branch that I have pushed?

https://dart.dev/tools/pub/dependencies#git-packages

**Comment by Skycoder42** [comment] 2022-10-26 06:05
@tnc1997 I just tried it out and now everything seems to work, thank you!

**Closed** 2022-10-26 18:01 UTC
