### ISSUE TITLE
Only deserialize fields with an annotation in generate from XML element

### ISSUE THREAD

**Issue by Skycoder42** [tnc1997/dart-xml-serializable#27] opened 2022-10-26 06:11 UTC
**Is your feature request related to a problem? Please describe.**
I have a class with computed fields (getters). However, when I try to add a getter with computed logic, the generator fails with the error:

```
[SEVERE] xml_serializable on lib/src/api/login/models/computed.dart:

Invalid argument (element): `isValid` does not have a supported annotation. Add an annotation of the form `@XmlAttribute()`, `@XmlElement()`, or `@XmlText()` to `isValid`.: Instance of 'FieldElementImpl'
```

Here is the corresponding code:

```dart
@xml.XmlSerializable(createMixin: true)
@xml.XmlRootElement(name: 'Computed')
@immutable
class Computed with _$ComputedXmlSerializableMixin {
  @xml.XmlText()
  final String value;

  bool get isValid => value != 'invalid';

  const Computed({required this.value});

  factory Computed.fromXmlElement(XmlElement element) =>
      _$ComputedFromXmlElement(element);
}
```

**Describe the solution you'd like**
It would be nice if there was a `XmlIgnore` annotation (or something similar) so we could simply exclude such members from the generator:

```dart
  @xml.XmlIgnore()
  bool get isValid => value != 'invalid';
```

**Describe alternatives you've considered**
Another alternative would be to only take members with a Xml annotation into account and implicitly ignore members without it, but I think I would prefer an "ignore" annotation.

**Comment by Skycoder42** [comment] 2022-10-26 06:13
As a workaround, I did the following. It works, but is not very intuitive:

```dart
@xml.XmlSerializable(createMixin: true)
@xml.XmlRootElement(name: 'Computed')
@immutable
class Computed extends _IComputed
    with _$ComputedXmlSerializableMixin, _ComputedGetters {
  @override
  @xml.XmlText()
  final String value;

  const Computed({required this.value});

  factory Computed.fromXmlElement(XmlElement element) =>
      _$ComputedFromXmlElement(element);
}

abstract class _IComputed {
  const _IComputed();

  String get value;
}

mixin _ComputedGetters on _IComputed {
  bool get isValid => value != 'invalid';
}
```

**Comment by tnc1997** [comment] 2022-10-27 18:15
Hi @Skycoder42, thank you very much for reporting this bug, I will aim to develop and release a fix this week.

It looks like this bug is caused by the [`_generateFromXmlElement`](https://github.com/tnc1997/dart-xml-serializable/blob/81508e096c8d59e3dcb66e446a5fe7a87d7bd36f/xml_serializable/lib/src/xml_serializable_generator.dart#L152-L156) method attempting to deserialize all the fields.

The intended behaviour is for the generator to only generate serializers and deserializers for annotated fields.

**Comment by tnc1997** [comment] 2022-10-29 06:17
Hi @Skycoder42, could I get you to verify that the issue is resolved by the changes on the branch that I have pushed?

https://dart.dev/tools/pub/dependencies#git-packages

**Comment by Skycoder42** [comment] 2022-10-29 13:46
Hi @tnc1997. I tried out the branch and it now works as accepted. Custom fields, private fields, getters, setters and static members all are correctly skipped by the generator and the generated code seems to work as well as it did before.

Thank you for your quick response and this awesome generator. Saved me a bunch of work an time!

**Comment by tnc1997** [comment] 2022-10-29 14:27
> Thank you for your quick response and this awesome generator. Saved me a bunch of work an time!

No problem at all, glad that it's useful!

Thank you for using the package and taking the time to report bugs 😄

**Closed** 2022-10-29 14:28 UTC
